### ISSUE TITLE
Docs link is missing on website

### ISSUE THREAD

**Issue by hairyhum** [kanisterio/website#1]
Currently the only link to docs.kanister.io is in a hidden div and there is no way to navigate to the docs from the website.

Since most of docs are in docs.kanister.io there should be a link navigable from kanister.io index page.

**Comment by hairyhum** [comment]
@mlavi I don't have permission to assign people, please take a look.

**Comment by mlavi** [comment]
Yes, now I see that the navigation menu was hidden.
I've added documentation links and other updates in progress now.

**Comment by mlavi** [comment]
Done: https://github.com/kanisterio/website/actions/runs/8543293858
